version: "3.0"
services:
  db:
    container_name: "db"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5444:5432"
    networks:
      - custom

  cft_test_app:
    container_name: cft_test_app
    image: cft_test_app # Specify the name of the Docker image to be built
    depends_on:
      - db
    environment:
      REAL_DATABASE_URL: "postgresql+asyncpg://postgres:postgres@db:5444/postgres"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - custom

networks:
  custom:
    driver: bridge
